# src/auth_context/infrastructure/google_oauth_client.py
import os
import logging
from typing import Dict, Optional, Tuple, List # Added List for scopes

from google_auth_oauthlib.flow import Flow
from google.oauth2.credentials import Credentials
from google.auth.transport.requests import Request as GoogleAuthRequest # Alias to avoid FastAPI Request

logger = logging.getLogger(__name__)

class GoogleOAuthClient:
    """
    Client for handling Google OAuth 2.0 Authorization Code Grant flow,
    specifically for accessing Gmail API.
    """
    def __init__(self):
        self.client_id = os.environ.get("GOOGLE_CLIENT_ID")
        self.client_secret = os.environ.get("GOOGLE_CLIENT_SECRET")
        self.redirect_uri = os.environ.get("GOOGLE_REDIRECT_URI") # This is the backend callback URI

        default_scopes_str = "https://www.googleapis.com/auth/gmail.readonly openid email profile"
        self.scopes_str = os.environ.get("GOOGLE_SCOPES", default_scopes_str)
        self.scopes_list: List[str] = self.scopes_str.split()

        if not all([self.client_id, self.client_secret, self.redirect_uri]):
            msg = "Google OAuth credentials (GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, GOOGLE_REDIRECT_URI) are not fully configured."
            logger.error(msg)
            raise ValueError(msg)

        # Client config for the flow, constructed in a way that `Flow.from_client_config` expects
        self.client_config = {
            "web": {
                "client_id": self.client_id,
                "client_secret": self.client_secret,
                "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                "token_uri": "https://oauth2.googleapis.com/token",
                "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
                # "redirect_uris" list is also part of client_secrets.json, but flow.redirect_uri is set explicitly later.
                # Ensure self.redirect_uri is one of the URIs registered in your Google Cloud Console.
                "redirect_uris": [self.redirect_uri],
            }
        }
        logger.info(f"GoogleOAuthClient initialized. Client ID: {self.client_id[:4]}..., Scopes: {self.scopes_list}, Redirect URI: {self.redirect_uri}")


    def get_authorization_request_url(self, state: str) -> Tuple[str, str]:
        """
        Generates the authorization URL to redirect the user to Google's login page.
        'state' is crucial for CSRF protection and should be generated by the caller (e.g., API endpoint).

        Returns:
            Tuple[str, str]: A tuple containing:
                - authorization_url (str): The URL to redirect the user to.
                - state_passed_to_flow (str): The state parameter that was passed to the flow,
                                              which should match the input 'state'.
        """
        flow = Flow.from_client_config(
            client_config=self.client_config,
            scopes=self.scopes_list,
            state=state  # Pass the externally generated state here for CSRF protection
        )
        # This redirect_uri must be one of the ones registered in the Google Cloud Console for your client ID.
        flow.redirect_uri = self.redirect_uri

        # `access_type='offline'` is crucial for obtaining a refresh token.
        # `prompt='consent'` can be used to ensure the refresh token is issued on first authorization
        # and sometimes on re-authorization if scopes change or user revoked access.
        # Some applications use `prompt='select_account'` to allow user to choose account every time.
        authorization_url, generated_state_from_flow = flow.authorization_url(
            access_type='offline',
            prompt='consent'
        )
        logger.debug(f"Generated Google auth URL: {authorization_url}. State used in flow: {generated_state_from_flow}")
        # The state returned by flow.authorization_url should be the same as the one passed in.
        # The caller (API endpoint) is responsible for storing this state (e.g., in a signed cookie)
        # and verifying it against the state received in the callback.
        return authorization_url, generated_state_from_flow

    def fetch_tokens_by_auth_code(self, authorization_response_url: str) -> Optional[Dict[str, Any]]:
        """
        Exchanges an authorization code (from the authorization_response_url) for tokens.
        The 'state' parameter from the authorization_response_url should be verified by the caller
        against the originally stored state *before* calling this method.

        Args:
            authorization_response_url (str): The full callback URL received by the application,
                                              containing the 'code' and 'state' query parameters.
        Returns:
            Optional[Dict[str, Any]]: A dictionary containing the tokens if successful, else None.
                                      Keys include: "access_token", "refresh_token", "id_token",
                                      "scopes", "expires_at" (custom added: ISO string of expiry datetime).
        """
        try:
            # The 'state' for CSRF protection should be verified by the caller *before* this method.
            # This `Flow` instance is created without `state` because `fetch_token` doesn't use it for validation here;
            # it expects `authorization_response` to be the full URL from which it extracts the code.
            # The state validation is a layer above this, handled by the API endpoint.
            flow = Flow.from_client_config(
                client_config=self.client_config,
                scopes=self.scopes_list
            )
            flow.redirect_uri = self.redirect_uri # Must match what was used in authorization_url

            # This method exchanges the code for tokens.
            flow.fetch_token(authorization_response=authorization_response_url)

            credentials = flow.credentials
            if not credentials or not credentials.valid:
                logger.error("Failed to fetch valid credentials from Google using auth code.")
                return None

            token_response = {
                "access_token": credentials.token,
                "refresh_token": credentials.refresh_token, # Crucial: This might be None if not first auth or 'offline' not used correctly.
                "id_token": getattr(credentials, 'id_token', None), # Raw ID token JWT
                "id_token_claims": credentials.id_token_jwt if hasattr(credentials, 'id_token_jwt') else None, # Decoded ID token claims
                "scopes": list(credentials.scopes) if credentials.scopes else [],
                "expires_at_datetime": credentials.expiry, # UTC datetime object
                "expires_at_iso": credentials.expiry.isoformat() if credentials.expiry else None,
            }
            logger.info(f"Successfully fetched Google tokens for user. Refresh token present: {bool(credentials.refresh_token)}. Access token expires at: {token_response['expires_at_iso']}")
            return token_response
        except Exception as e:
            # This can catch google.auth.exceptions.OAuth2Error for issues like 'invalid_grant' (bad code, redirect_uri mismatch),
            # or state mismatch if state was passed to Flow here AND to fetch_token.
            logger.error(f"Exception in fetch_tokens_by_auth_code: {e}", exc_info=True)
            return None

    def refresh_access_token(self, refresh_token: str) -> Optional[Dict[str, Any]]:
        """
        Refreshes an access token using a Google refresh token.
        """
        try:
            credentials = Credentials(
                token=None, # No initial access token
                refresh_token=refresh_token,
                token_uri=self.client_config["web"]["token_uri"],
                client_id=self.client_id,
                client_secret=self.client_secret,
                scopes=self.scopes_list # Scopes might be needed for some providers or if they changed
            )

            # Create a transport request object for the refresh call
            auth_request = GoogleAuthRequest()
            credentials.refresh(auth_request) # This makes the refresh API call

            if not credentials.valid or not credentials.token:
                logger.error("Failed to refresh Google access token. Credentials invalid or token missing after refresh.")
                return None

            token_response = {
                "access_token": credentials.token,
                # Google typically does NOT return a new refresh token on every access token refresh.
                # The original refresh_token should be re-used unless it's explicitly revoked or expired.
                "refresh_token": credentials.refresh_token, # This will likely be None. Store the original one.
                "scopes": list(credentials.scopes) if credentials.scopes else [],
                "expires_at_datetime": credentials.expiry, # UTC datetime object
                "expires_at_iso": credentials.expiry.isoformat() if credentials.expiry else None,
                "id_token": getattr(credentials, 'id_token', None), # ID token might be reissued
                "id_token_claims": credentials.id_token_jwt if hasattr(credentials, 'id_token_jwt') else None,
            }
            logger.info(f"Successfully refreshed Google access token. New expiry: {token_response['expires_at_iso']}")
            return token_response
        except Exception as e: # Catches google.auth.exceptions.RefreshError if refresh token is invalid/expired
            logger.error(f"Exception refreshing Google access token: {e}", exc_info=True)
            return None

# Example usage (conceptual)
if __name__ == '__main__':
    print("GoogleOAuthClient demonstration (conceptual):")
    required_env_vars = ["GOOGLE_CLIENT_ID", "GOOGLE_CLIENT_SECRET", "GOOGLE_REDIRECT_URI"]
    if not all(os.environ.get(var) for var in required_env_vars):
        print(f"Skipping demo: Set required env vars: {', '.join(required_env_vars)}")
    else:
        try:
            client = GoogleOAuthClient()
            print(f"Client initialized. Scopes: {client.scopes_list}")
            auth_url, state = client.get_authorization_request_url(state="test_google_state_123")
            print(f"\n1. Authorization URL (redirect user here):\n   {auth_url}")
            print(f"   State passed to flow: {state}")
            print("\n2. After user auth, Google redirects to your GOOGLE_REDIRECT_URI with 'code' and 'state'.")
            print("   Your callback handler would then call fetch_tokens_by_auth_code(full_callback_url).")
            # Example: fetch_tokens_by_auth_code("https://your.app/callback?code=XYZ&state=test_google_state_123")
            print("\n3. To refresh, use client.refresh_access_token('stored_refresh_token').")
        except ValueError as e:
            print(f"Error during client initialization: {e}")
        except Exception as e:
            print(f"An unexpected error: {e}")
```
