# src/auth_context/infrastructure/m365_oauth_client.py
import os
import logging
import msal
from typing import Dict, Optional, Tuple, List # Added List for scopes

# Configure basic logging for this client
# In a larger app, logging would be configured more centrally.
logger = logging.getLogger(__name__)
# To see debug messages from this client during development:
# if not logger.handlers:
#     handler = logging.StreamHandler()
#     formatter = logging.Formatter('%(asctime)s - %(name)s - %(levelname)s - %(message)s')
#     handler.setFormatter(formatter)
#     logger.addHandler(handler)
#     logger.setLevel(logging.DEBUG) # Set to DEBUG for this client's messages
# else: # Ensure level is appropriate if handlers exist
#     logger.setLevel(logging.DEBUG)


class M365OAuthClient:
    """
    Client for handling Microsoft 365 OAuth 2.0 Authorization Code Grant flow.
    This client helps in generating authorization URLs and acquiring tokens.
    """
    def __init__(self):
        self.client_id = os.environ.get("AZURE_CLIENT_ID")
        self.client_secret = os.environ.get("AZURE_CLIENT_SECRET")
        self.tenant_id = os.environ.get("AZURE_TENANT_ID")

        # Construct authority URL. For multi-tenant apps, 'common' or 'organizations' might be used instead of tenant_id.
        # For single-tenant or if tenant_id is correctly set for the desired audience:
        self.authority = f"https://login.microsoftonline.com/{self.tenant_id}"

        self.redirect_uri = os.environ.get("M365_REDIRECT_URI")
        if not self.redirect_uri:
            msg = "M365_REDIRECT_URI environment variable is not set. This is required for OAuth flow."
            logger.error(msg)
            raise ValueError(msg)

        default_scopes_str = "User.Read Mail.Read offline_access" # Common default scopes
        self.scopes_str = os.environ.get("M365_SCOPES", default_scopes_str)
        self.scopes: List[str] = self.scopes_str.split() # Convert space-separated string to list

        if not all([self.client_id, self.client_secret, self.tenant_id]):
            msg = "Azure AD app credentials (AZURE_CLIENT_ID, AZURE_CLIENT_SECRET, AZURE_TENANT_ID) are not fully configured."
            logger.error(msg)
            raise ValueError(msg)

        # Initialize MSAL ConfidentialClientApplication
        # Token cache can be passed here if server-side token caching strategy is implemented.
        # For user tokens, typically they are stored associated with the user's session/profile.
        self.msal_app = msal.ConfidentialClientApplication(
            client_id=self.client_id,
            authority=self.authority,
            client_credential=self.client_secret,
            # token_cache=msal.SerializableTokenCache() # Example for a serializable cache
        )
        logger.info(f"M365OAuthClient initialized for tenant '{self.tenant_id}', client_id '{self.client_id[:4]}...'. Redirect URI: {self.redirect_uri}")

    def get_authorization_request_url(self, state: Optional[str] = None) -> Tuple[str, str]:
        """
        Generates the Microsoft identity platform authorization request URL.
        The application should redirect the user to this URL.

        Args:
            state (Optional[str]): A unique, securely generated value used to prevent CSRF attacks.
                                   If None, MSAL may generate one, but it's recommended for the caller
                                   to generate, store (e.g., in session), and verify it upon callback.

        Returns:
            Tuple[str, str]: A tuple containing:
                - authorization_url (str): The URL to redirect the user to.
                - state (str): The state parameter used in the flow (either passed in or generated by MSAL).
                               Caller must store this to verify against the callback.
        """
        # MSAL's initiate_auth_code_flow prepares the parameters for the authorization request.
        # It's crucial to store the 'state' (and potentially 'pkce_verifier' if using PKCE, though
        # ConfidentialClientApplication typically doesn't rely on PKCE as client secret is used)
        # in a way that can be retrieved during the callback phase (e.g., user session).
        auth_flow_details = self.msal_app.initiate_auth_code_flow(
            scopes=self.scopes,
            redirect_uri=self.redirect_uri,
            state=state
        )
        logger.debug(f"Initiated MSAL auth code flow. Auth URI: {auth_flow_details['auth_uri']}, State: {auth_flow_details['state']}")
        # It's important to save auth_flow_details (or at least auth_flow_details['state'])
        # in the user's session or a temporary server-side cache, keyed by 'state' or user session ID,
        # so it can be retrieved and used in acquire_token_by_auth_code_flow.
        return auth_flow_details["auth_uri"], auth_flow_details["state"]

    def acquire_token_by_auth_code_flow(self, auth_code_flow_session_details: Dict, auth_response_params: Dict) -> Optional[Dict]:
        """
        Acquires an access token, refresh token, and ID token using the authorization code
        received from Microsoft identity platform after user consent.

        Args:
            auth_code_flow_session_details (Dict): The flow details dictionary that was initiated by
                                                   `initiate_auth_code_flow` and should have been stored
                                                   (e.g., in the user's session). This includes the 'state'.
            auth_response_params (Dict): A dictionary-like object containing the query parameters
                                         received by your application's redirect URI (callback endpoint).
                                         This must include the 'code' and 'state'.

        Returns:
            Optional[Dict]: A dictionary containing the tokens (access_token, refresh_token, id_token, etc.)
                            if successful, otherwise None if an error occurs.
        """
        try:
            # MSAL will use the 'state' from auth_code_flow_session_details to validate against
            # the 'state' in auth_response_params.
            token_response = self.msal_app.acquire_token_by_auth_code_flow(
                auth_code_flow=auth_code_flow_session_details, # The stashed flow details
                auth_response=auth_response_params,        # The query parameters from the redirect
                scopes=self.scopes                         # Scopes can be re-specified if needed
            )

            if "error" in token_response:
                err_desc = token_response.get('error_description', 'No error description provided.')
                logger.error(f"Error acquiring token via auth code flow: {token_response.get('error')}. Description: {err_desc}")
                return None

            logger.info(f"Successfully acquired token for user (id_token claims: {token_response.get('id_token_claims', {}).get('oid')}). Access token type: {token_response.get('token_type')}")
            # Token response typically contains: access_token, refresh_token, id_token, expires_in, scope, token_type.
            # It's important to securely store the refresh_token (associated with the user) for later use.
            # The id_token contains claims about the user (sub, name, email, etc.).
            return token_response

        except ValueError as ve: # MSAL can raise ValueError for state mismatch or other issues
            logger.error(f"ValueError during acquire_token_by_auth_code_flow (e.g., state mismatch): {ve}", exc_info=True)
            return None
        except Exception as e:
            logger.error(f"Unexpected exception in acquire_token_by_auth_code_flow: {e}", exc_info=True)
            return None

    def acquire_token_by_refresh_token(self, refresh_token: str, scopes_override: Optional[List[str]] = None) -> Optional[Dict]:
        """
        Acquires a new access token (and potentially a new refresh token) using a previously obtained refresh token.

        Args:
            refresh_token (str): The refresh token.
            scopes_override (Optional[List[str]]): Optional list of scopes if different from default.
                                                   Usually, for refresh tokens, scopes are not re-specified
                                                   unless you are requesting tokens for a *different* resource
                                                   or incrementally consenting to new scopes (which has limitations).
                                                   For Graph, typically stick to original scopes or subset.

        Returns:
            Optional[Dict]: A dictionary containing the new tokens if successful, otherwise None.
        """
        effective_scopes = scopes_override if scopes_override else self.scopes
        try:
            token_response = self.msal_app.acquire_token_by_refresh_token(
                refresh_token=refresh_token,
                scopes=effective_scopes
            )

            if "error" in token_response:
                err_desc = token_response.get('error_description', 'No error description provided.')
                logger.error(f"Error acquiring token by refresh token: {token_response.get('error')}. Description: {err_desc}")
                # This could mean the refresh token is invalid, expired, or revoked.
                return None

            logger.info("Successfully acquired new token(s) using refresh token.")
            # A new refresh token might be issued; if so, the application should store and use the new one.
            # If token_response does not contain 'refresh_token', the old one is still valid.
            return token_response

        except Exception as e:
            logger.error(f"Exception in acquire_token_by_refresh_token: {e}", exc_info=True)
            return None

# Example usage (for understanding, not for direct execution without context)
if __name__ == '__main__':
    # This client is meant to be used within a web application flow.
    # Direct execution here won't work without a user interaction and callback.
    print("M365OAuthClient demonstration (conceptual):")

    # Check if required environment variables are set for basic initialization test
    required_env_vars = ["AZURE_CLIENT_ID", "AZURE_CLIENT_SECRET", "AZURE_TENANT_ID", "M365_REDIRECT_URI"]
    if not all(os.environ.get(var) for var in required_env_vars):
        print("Skipping M365OAuthClient instantiation demo: Required environment variables are not set.")
        print(f"Please set: {', '.join(required_env_vars)}")
    else:
        try:
            client = M365OAuthClient()
            print(f"Client initialized. Authority: {client.authority}, Scopes: {client.scopes}")

            # 1. Get Authorization URL (Application redirects user here)
            # In a real app, 'test_state' would be generated, stored in user's session,
            # and verified on callback.
            auth_url, state_out = client.get_authorization_request_url(state="test_state_12345")
            print(f"\n1. Authorization URL (redirect user here):\n   {auth_url}")
            print(f"   State generated/used: {state_out} (store this in user session to verify later)")

            # --- User authenticates, consents, and is redirected back to M365_REDIRECT_URI ---
            # The redirect URI will receive 'code' and 'state' as query parameters.

            # 2. Acquire Token (Simulated callback - this part cannot run without actual redirection)
            print("\n2. Simulating token acquisition (requires actual user auth & redirect):")
            print("   - User authenticates with Microsoft and consents.")
            print(f"   - Microsoft redirects back to: {client.redirect_uri}?code=SOME_AUTH_CODE&state={state_out}")

            # Example: This is what your callback endpoint would receive and do:
            # auth_code_flow_from_session = { ... 'state': state_out ... } # Retrieved from user session
            # auth_response_from_redirect = {'code': 'SOME_AUTH_CODE', 'state': state_out, ...}
            # token_package = client.acquire_token_by_auth_code_flow(auth_code_flow_from_session, auth_response_from_redirect)
            # if token_package:
            #     print("\n   Tokens acquired (example structure):")
            #     print(f"     Access Token: {token_package.get('access_token')[:20]}...")
            #     print(f"     Refresh Token: {token_package.get('refresh_token')[:20]}...") # Store securely!
            #     print(f"     ID Token (claims): {token_package.get('id_token_claims')}")
            # else:
            #     print("\n   Failed to acquire tokens from auth code.")

            # 3. Refresh Token (Simulated - requires a valid refresh token)
            # print("\n3. Simulating token refresh (requires a valid refresh_token):")
            # example_refresh_token = "previously_obtained_refresh_token_here"
            # new_token_package = client.acquire_token_by_refresh_token(example_refresh_token)
            # if new_token_package:
            #     print("\n   Tokens refreshed (example structure):")
            #     print(f"     New Access Token: {new_token_package.get('access_token')[:20]}...")
            #     if new_token_package.get('refresh_token'):
            #         print(f"     New Refresh Token: {new_token_package.get('refresh_token')[:20]}...") # Store this new one!
            # else:
            #     print("\n   Failed to refresh tokens.")
        except ValueError as e:
            print(f"Error during client initialization: {e}")
        except Exception as e:
            print(f"An unexpected error occurred during demonstration: {e}")

    print("\nNote: Full OAuth flow requires browser interaction and a callback endpoint.")
```
