# src/auth_context/application/auth_service.py
from fastapi import HTTPException, status # For raising HTTP exceptions

from ..domain.user import User
from ..infrastructure.user_repository import MongoUserRepository
from .security import hash_password, verify_password
# create_access_token is typically called by the API router, not the service directly
from src.api.v1.schemas.auth_schemas import UserCreate # For type hinting user_create

class AuthService:
    """
    Application service for authentication and user management.
    """
    def __init__(self, user_repository: MongoUserRepository):
        self.user_repository = user_repository

    def register_user(self, user_create_schema: UserCreate) -> User:
        """
        Registers a new user.
        Checks for existing username, hashes password, creates User domain object,
        and saves to repository.
        """
        print(f"AuthService: Attempting to register user: {user_create_schema.username}")
        existing_user = self.user_repository.get_by_username(user_create_schema.username)
        if existing_user:
            print(f"AuthService: User '{user_create_schema.username}' already exists.")
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Username already registered."
            )

        hashed_user_password = hash_password(user_create_schema.password)

        # Create User domain object
        # ID will be auto-generated by User dataclass default factory
        new_user = User(
            username=user_create_schema.username,
            hashed_password=hashed_user_password,
            is_active=True # Default to active, could be part of UserCreate schema or an admin action later
        )

        # Save user via repository
        # The repository's add method returns bool, but here we might want to ensure it worked
        # or let exceptions from repo propagate if they occur (e.g., DB connection issue)
        if not self.user_repository.add(new_user):
            # This case might be rare if username check passed and DB is up,
            # but could happen if e.g. duplicate key error was not caught by get_by_username due to race condition (unlikely with index)
            # or other repo internal issue.
            print(f"AuthService: Failed to save new user '{new_user.username}' to repository.")
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Could not create user due to a storage error."
            )

        print(f"AuthService: User '{new_user.username}' registered successfully with ID {new_user.id}.")
        return new_user

    def authenticate_user(self, username: str, password_to_verify: str) -> Optional[User]:
        """
        Authenticates a user.
        Retrieves user by username and verifies password.
        """
        print(f"AuthService: Attempting to authenticate user: {username}")
        user = self.user_repository.get_by_username(username)
        if not user:
            print(f"AuthService: Authentication failed - user '{username}' not found.")
            return None # User not found

        if not user.is_active: # Check if user is active before verifying password
            print(f"AuthService: Authentication failed - user '{username}' is inactive.")
            return None

        if not verify_password(password_to_verify, user.hashed_password):
            print(f"AuthService: Authentication failed - incorrect password for user '{username}'.")
            return None # Incorrect password

        print(f"AuthService: User '{username}' authenticated successfully.")
        return user

# Example (for direct testing, not part of production flow)
if __name__ == '__main__':
    print("--- AuthService Demonstration ---")
    # This requires a running MongoDB instance for MongoUserRepository
    try:
        # Setup a mock repository or a real one for testing
        # For this demo, let's assume MongoUserRepository can connect or will print errors
        mock_user_repo = MongoUserRepository() # Default connection
        if mock_user_repo.collection is None:
            print("Skipping AuthService demo as MongoDB connection failed for UserRepository.")
        else:
            # Ensure test user doesn't exist from previous runs
            mock_user_repo.collection.delete_many({"username": {"$regex": "^auth_service_test"}})
            print("Cleaned up previous AuthService test users if any.")

            auth_service_instance = AuthService(user_repository=mock_user_repo)

            # 1. Register a new user
            print("\nTesting user registration:")
            test_user_data = UserCreate(username="auth_service_test@example.com", password="StrongPassword123")
            try:
                created_user = auth_service_instance.register_user(test_user_data)
                print(f"Registered user: {created_user.username}, ID: {created_user.id}")
                assert created_user.username == test_user_data.username

                # Try registering the same user again (should fail)
                print("\nTesting duplicate registration (expected failure):")
                auth_service_instance.register_user(test_user_data) # Expected HTTPException
            except HTTPException as http_exc:
                print(f"Caught expected HTTPException: {http_exc.status_code} - {http_exc.detail}")
                assert http_exc.status_code == status.HTTP_400_BAD_REQUEST

            # 2. Authenticate user - correct password
            print("\nTesting authentication (correct password):")
            authenticated_user = auth_service_instance.authenticate_user(
                test_user_data.username,
                test_user_data.password
            )
            if authenticated_user:
                print(f"Authenticated user: {authenticated_user.username}")
                assert authenticated_user.username == test_user_data.username
            else:
                print("Authentication failed (unexpected).")

            # 3. Authenticate user - incorrect password
            print("\nTesting authentication (incorrect password):")
            auth_fail_password = auth_service_instance.authenticate_user(
                test_user_data.username,
                "WrongPassword!"
            )
            print(f"Authentication with wrong password successful: {auth_fail_password is not None} (expected False)")
            assert auth_fail_password is None

            # 4. Authenticate non-existent user
            print("\nTesting authentication (non-existent user):")
            auth_fail_nouser = auth_service_instance.authenticate_user(
                "nosuch_auth_user@example.com",
                "anypassword"
            )
            print(f"Authentication for non-existent user successful: {auth_fail_nouser is not None} (expected False)")
            assert auth_fail_nouser is None

            # 5. Test inactive user authentication
            print("\nTesting inactive user authentication:")
            inactive_user_data = UserCreate(username="inactive_auth_test@example.com", password="Password123")
            inactive_user = auth_service_instance.register_user(inactive_user_data)
            print(f"Registered inactive test user: {inactive_user.username}")
            # Manually set user to inactive in DB for test
            mock_user_repo.collection.update_one({"id": inactive_user.id}, {"$set": {"is_active": False}})
            auth_fail_inactive = auth_service_instance.authenticate_user(inactive_user.username, inactive_user_data.password)
            print(f"Authentication for inactive user successful: {auth_fail_inactive is not None} (expected False)")
            assert auth_fail_inactive is None


            # Clean up test users
            mock_user_repo.collection.delete_many({"username": {"$regex": "^auth_service_test"}})
            mock_user_repo.collection.delete_many({"username": "inactive_auth_test@example.com"})
            print("\nCleaned up AuthService test users.")

    except Exception as e:
        print(f"Error during AuthService demonstration: {e}")
        print("Ensure MongoDB is running and accessible for this demo.")

    print("\n--- End of AuthService Demonstration ---")
