# src/activity_log_context/application/log_service.py

from ..domain.activity_record import ActivityRecord
from ..infrastructure import MongoActivityRepository # Import the concrete repository
from src.shared_kernel.events import ContentAnalyzedEvent # For type hinting the new method

import datetime
import uuid # For generating record_id if needed, though ActivityRecord handles it

# For type hints if RawEmail/AnalyzedContent objects were directly passed (not current approach for event method)
from typing import TYPE_CHECKING
if TYPE_CHECKING:
    from src.ingestion_context.domain.raw_email import RawEmail
    from src.analysis_context.domain.analyzed_content import AnalyzedContent


class LogService:
    """
    Application service for the Activity Log Context.
    Orchestrates the creation and storage of activity log records using a repository.
    """
    def __init__(self, activity_log_repo: MongoActivityRepository | None = None):
        """
        Initializes the LogService.

        Args:
            activity_log_repo (MongoActivityRepository, optional):
                An instance of the activity log repository.
                If None, a default MongoActivityRepository will be created.
        """
        if activity_log_repo:
            self.activity_log_repo = activity_log_repo
        else:
            # Default instantiation if no repo is provided (e.g., for convenience in smaller setups)
            # This will try to connect to MongoDB with default/env var settings.
            self.activity_log_repo = MongoActivityRepository()

        if self.activity_log_repo.collection is None:
            print("LogService initialized, but MongoActivityRepository failed to connect. Logging will not work.")
        else:
            print("LogService initialized with MongoActivityRepository.")

    def record_activity_from_event_data(self, event: ContentAnalyzedEvent) -> ActivityRecord | None:
        """
        Creates an ActivityRecord from the data provided in a ContentAnalyzedEvent
        and saves it using the repository.
        """
        print(f"LogService: Received ContentAnalyzedEvent for raw_email_id: {event.raw_email_id}")
        try:
            # Create ActivityRecord instance from event data
            # The ActivityRecord.record_id will be auto-generated by its default factory.
            # The ActivityRecord.logged_at will also be auto-generated.
            activity = ActivityRecord(
                ingested_at=event.received_at,
                source_channel="email", # Assuming "email" for now, could be part of event
                source_identifier=event.source_identifier, # e.g., file path or original EML Message-ID
                sender=event.sender,
                recipient=event.recipient,
                subject=event.subject,
                summary=event.summary,
                disposition=event.disposition,
                # Example: Construct a reference, or it could be the raw_email_id itself
                full_content_reference=f"raw_email_id:{event.raw_email_id}",
                metadata={
                    "analyzed_at": event.analyzed_at,
                    "keywords_found": event.keywords_found,
                    "original_body_snippet": event.body[:200] if event.body else "" # Store a snippet
                }
            )

            save_success = self.activity_log_repo.add(activity)
            if save_success:
                print(f"LogService: Successfully saved ActivityRecord ID {activity.record_id} for raw_email_id {event.raw_email_id}")
                return activity
            else:
                print(f"LogService: Failed to save ActivityRecord for raw_email_id {event.raw_email_id}")
                return None
        except Exception as e:
            print(f"LogService: Error creating or saving ActivityRecord from event: {e}")
            return None

    # Kept the old method for direct calls if needed, but event-driven is preferred
    def create_log_from_processed_data(
        self,
        raw_email: 'RawEmail',
        analyzed_content: 'AnalyzedContent',
        source_channel: str = "email"
    ) -> ActivityRecord | None:
        print(f"LogService: Creating activity log directly for email ID: {raw_email.message_id}")
        activity_record = ActivityRecord.from_analysis(
            raw_email=raw_email,
            analyzed_content=analyzed_content,
            source_channel=source_channel
        )

        save_success = self.activity_log_repo.add(activity_record)
        if save_success:
            print(f"LogService: Direct save of ActivityRecord ID {activity_record.record_id} successful.")
            return activity_record
        else:
            print(f"LogService: Direct save of ActivityRecord ID {activity_record.record_id} failed.")
            return None


# Example Usage (for testing LogService with its new method)
if __name__ == '__main__':
    print("\n--- LogService with Event Data Method Demonstration ---")

    # This test assumes MongoDB is running, as LogService initializes MongoActivityRepository.
    # If MongoDB is not running, the repository init will print errors, and add will fail.
    log_service_instance = LogService()

    if log_service_instance.activity_log_repo.collection is not None:
        # Simulate a ContentAnalyzedEvent
        simulated_event_data = ContentAnalyzedEvent(
            raw_email_id="logservice-test-001",
            sender="event_sender@example.com",
            recipient="event_recipient@example.com",
            subject="LogService Event Test",
            body="This is original body for LogService test.",
            received_at=datetime.datetime.now(datetime.timezone.utc).isoformat(),
            source_identifier="/path/to/logservice_test.eml",
            summary="This is a summary from analysis.",
            disposition="TestDisposition",
            keywords_found=["logservice", "test"],
            analyzed_at=datetime.datetime.now(datetime.timezone.utc).isoformat()
        )

        print(f"\nAttempting to log activity from simulated event for ID: {simulated_event_data.raw_email_id}")
        logged_activity = log_service_instance.record_activity_from_event_data(simulated_event_data)

        if logged_activity:
            print(f"\nActivityRecord created and attempted save by LogService:")
            print(f"  Record ID: {logged_activity.record_id}")
            print(f"  Subject: {logged_activity.subject}")
            print(f"  Disposition: {logged_activity.disposition}")
            print(f"  Logged At: {logged_activity.logged_at}")
            # To verify, you'd check MongoDB or mock the repository's add method in a unit test.
        else:
            print("Logging activity from event failed or was skipped due to repository issue.")
    else:
        print("\nSkipping LogService operations as MongoDB connection seems to have failed during initialization.")

    print("\n--- End of LogService Demonstration ---")
